### PR TITLE
Switch to background service

### PR DESCRIPTION
**Pull request by danielmarbach**
I haven't had time to fully test this. I did these changes while sitting at a conference. Take it with some grain of salt

### CODE REVIEW

**Comment by enzian** [comment]
I gave it a look and it seems like `ExecuteAsync` is never called...

**Comment by danielmarbach** [comment]
That is weird. According to https://github.com/aspnet/Hosting/blob/master/src/Microsoft.Extensions.Hosting.Abstractions/BackgroundService.cs#L33 it should

Ah see the problem. Will fix

**Comment by danielmarbach** [comment]
@enzian have a look

**Comment by enzian** [comment]
had the same idea, but, now the interrupt signal is not processed anymore because there are no await sections in the main polling loop! Pressing Ctrl+C does not terminate the host and no startup diagnostics are shown...

Extracting the main Polling loop into its own task and interrupting that task with the `stoppingToken` could work though!

Why couldn't kafka just offer an async polling interface!

**Comment by enzian** [comment]
This works as intended:
```csharp
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    await Task.Run(async () =>
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            consumer.Consume(out var msg, TimeSpan.FromSeconds(1));
            if (msg != null)
            {
                logger.LogDebug($"Received message from topic '{msg.Topic}:{msg.Partition}' with offset: '{msg.Offset}[{msg.TopicPartitionOffset}]'");

                using (var scope = serviceProvider.CreateScope())
                {
                    var handler = scope.ServiceProvider.GetService<IKafkaMessageHandler<TKey, TValue>>();
                    if (handler == null)
                    {
                        logger.LogError("Failed to resolve message handler. Did you add it to your DI setup.");
                        continue;
                    }
                    try
                    {
                        // Invoke the handler
                        await handler.Handle(msg);
                    }
                    catch (Exception e)
                    {
                        logger.LogError(e, "Message handler failed:");
                        continue;
                    }
                }
            }
            else
            {
                logger.LogDebug("No messages received");
            }
        }
    });
}
```

**Comment by enzian** [comment]
I took the liberty of extending your code and merging it! (and also squashed `1b4142a` ;-) )

**Comment by danielmarbach** [comment]
Yeah I can see how the offloading is needed here. I did not go that deep into the code. Nice find

**Comment by enzian** [comment]
Thank you for your contribution :-)

**Comment by enzian** [comment]
BTW: Your contribution has already been released! The 1.1.0 packages can be found in the release section or on Nuget

**Pull request closed without merging**
